// Cada animal guarda o id de quem publicou (idUsuario) e o id do local onde está (idLocal).
// idade em anos; 0 = filhote com menos de um ano.
const listaDeAnimais = [
    {
        id: 1,
        nome: "Thor",
        categoria: "Cães",
        porte: "Grande",
        sexo: "Macho",
        idade: 3,
        idLocal: 5,
        idUsuario: 1,
        publicadoEm: "2026-10-02",
        vacinado: true,
        castrado: true,
        descricao: "Brincalhão e protetor. Precisa de quintal e de passeios diários.",
        img: "https://placedog.net/320/240?id=1"
    },
    {
        id: 2,
        nome: "Mel",
        categoria: "Cães",
        porte: "Pequeno",
        sexo: "Fêmea",
        idade: 1,
        idLocal: 1,
        idUsuario: 1,
        publicadoEm: "2026-10-05",
        vacinado: true,
        castrado: true,
        descricao: "Calma, se dá bem com crianças e outros cães.",
        img: "https://placedog.net/320/240?id=2"
    },
    {
        id: 3,
        nome: "Luna",
        categoria: "Gatos",
        porte: "Pequeno",
        sexo: "Fêmea",
        idade: 1,
        idLocal: 2,
        idUsuario: 2,
        publicadoEm: "2026-10-06",
        vacinado: true,
        castrado: true,
        descricao: "Curiosa e carinhosa. Usa caixa de areia.",
        img: "https://cataas.com/cat?width=320&height=240&n=3"
    },
    {
        id: 4,
        nome: "Bob",
        categoria: "Cães",
        porte: "Médio",
        sexo: "Macho",
        idade: 2,
        idLocal: 3,
        idUsuario: 2,
        publicadoEm: "2026-09-28",
        vacinado: true,
        castrado: false,
        descricao: "Resgatado da rua, já está adaptado a apartamento.",
        img: "https://placedog.net/320/240?id=4"
    },
    {
        id: 5,
        nome: "Nina",
        categoria: "Gatos",
        porte: "Pequeno",
        sexo: "Fêmea",
        idade: 5,
        idLocal: 4,
        idUsuario: 2,
        publicadoEm: "2026-09-30",
        vacinado: true,
        castrado: true,
        descricao: "Tranquila, ideal para quem passa o dia fora.",
        img: "https://cataas.com/cat?width=320&height=240&n=5"
    },
    {
        id: 6,
        nome: "Rex",
        categoria: "Cães",
        porte: "Grande",
        sexo: "Macho",
        idade: 6,
        idLocal: 8,
        idUsuario: 3,
        publicadoEm: "2026-09-25",
        vacinado: true,
        castrado: true,
        descricao: "Idoso e muito dócil. Procura um lar para a velhice.",
        img: "https://placedog.net/320/240?id=6"
    },
    {
        id: 7,
        nome: "Pipoca",
        categoria: "Cães",
        porte: "Pequeno",
        sexo: "Fêmea",
        idade: 0,
        idLocal: 6,
        idUsuario: 3,
        publicadoEm: "2026-10-07",
        vacinado: false,
        castrado: false,
        descricao: "Filhote de 4 meses, cheia de energia.",
        img: "https://placedog.net/320/240?id=7"
    },
    {
        id: 8,
        nome: "Fred",
        categoria: "Gatos",
        porte: "Médio",
        sexo: "Macho",
        idade: 2,
        idLocal: 8,
        idUsuario: 3,
        publicadoEm: "2026-10-01",
        vacinado: true,
        castrado: true,
        descricao: "Independente, gosta de janela com tela.",
        img: "https://cataas.com/cat?width=320&height=240&n=8"
    },
    {
        id: 9,
        nome: "Amora",
        categoria: "Cães",
        porte: "Médio",
        sexo: "Fêmea",
        idade: 1,
        idLocal: 7,
        idUsuario: 4,
        publicadoEm: "2026-10-03",
        vacinado: true,
        castrado: true,
        descricao: "Aprende rápido e adora brincar de bolinha.",
        img: "https://placedog.net/320/240?id=9"
    },
    {
        id: 10,
        nome: "Zeus",
        categoria: "Cães",
        porte: "Grande",
        sexo: "Macho",
        idade: 1,
        idLocal: 9,
        idUsuario: 4,
        publicadoEm: "2026-10-04",
        vacinado: true,
        castrado: false,
        descricao: "Jovem e forte. Indicado para quem já teve cães grandes.",
        img: "https://placedog.net/320/240?id=10"
    },
    {
        id: 11,
        nome: "Mia",
        categoria: "Gatos",
        porte: "Pequeno",
        sexo: "Fêmea",
        idade: 3,
        idLocal: 2,
        idUsuario: 4,
        publicadoEm: "2026-09-29",
        vacinado: true,
        castrado: true,
        descricao: "Dorminhoca e sociável com outros gatos.",
        img: "https://cataas.com/cat?width=320&height=240&n=11"
    },
    {
        id: 12,
        nome: "Toby",
        categoria: "Cães",
        porte: "Pequeno",
        sexo: "Macho",
        idade: 4,
        idLocal: 4,
        idUsuario: 2,
        publicadoEm: "2026-09-27",
        vacinado: true,
        castrado: true,
        descricao: "Companheiro, late pouco, acostumado a coleira.",
        img: "https://placedog.net/320/240?id=12"
    },
    {
        id: 13,
        nome: "Chico",
        categoria: "Gatos",
        porte: "Médio",
        sexo: "Macho",
        idade: 0,
        idLocal: 1,
        idUsuario: 1,
        publicadoEm: "2026-10-07",
        vacinado: false,
        castrado: false,
        descricao: "Filhote de 3 meses, já come ração seca.",
        img: "https://cataas.com/cat?width=320&height=240&n=13"
    },
    {
        id: 14,
        nome: "Pandora",
        categoria: "Cães",
        porte: "Médio",
        sexo: "Fêmea",
        idade: 7,
        idLocal: 3,
        idUsuario: 4,
        publicadoEm: "2026-09-20",
        vacinado: true,
        castrado: true,
        descricao: "Senhorinha tranquila, ótima para casa com idosos.",
        img: "https://placedog.net/320/240?id=14"
    }
]
export default listaDeAnimais;
